### PR TITLE
Fixed vulnerability in dependencies.

### LINKED ISSUE #36: Fix vulnerability in lodash
Report: https://snyk.io/test/github/vkkis93/serverless-step-functions-offline?targetFile=package.json

Resolution: lodash 4.17.11 -> 4.17.12

### PR DESCRIPTION
**Pull request by lukemcgregor**
Fixes #36 
lodash upgraded to 4.17.12
eslint version corrected to a valid one (4.17.0, looks like it was a copy paste mistake?)

### CODE REVIEW

**Comment by sojeri** [comment]
@vkkis93 -- any chance you'll integrate this?

**Comment by vkkis93** [comment]
@lukemcgregor thanks a lot!

**Comment by vkkis93** [comment]
@sojeri going to create new release in a few days.

**Comment by vkkis93** [comment]
fixed

**Pull request closed without merging**
