### PR TITLE
add variable interpolation and env vars

### PR DESCRIPTION
**Pull request by ajagnanan**
I ran into the issue where variables weren't interpolated when parsing the yaml file. I took the parser that's used here https://github.com/horike37/serverless-step-functions/blob/11134c93e1f705ef5ccc4127543d6f4bad959fc8/lib/yamlParser.js. I also added environment variable processing.

### CODE REVIEW

**Comment by ajagnanan** [comment]
could you add the eslint configuration file? I can fix those lint errors tomorrow most likely.

**Comment by vkkis93** [comment]
Hi @ajagnanan 
You are right I missed that.
Concerning your pull request, this code from https://github.com/horike37/serverless-step-functions/blob/11134c93e1f705ef5ccc4127543d6f4bad959fc8/lib/yamlParser.js is unnecessary for my package.
My code works in a little bit different way.

I'm working on the version 2.
This release will include fix about env variables.
I have added lines which loads env variables like: 
  `
        const environment = this.serverless.service.provider.environment;
        process.env = _.extend(process.env, environment);
    `
I hope it will be released this week.

I will close this pull request.
Is it ok for you ?
P.S Thank you for contribution

**Comment by ajagnanan** [comment]
gotcha, just an fyi for what I'm doing. Cloudformation has a max size limit that we usually run into. To overcome it, we usually separate the serverless file into 'stacks'. In this case I'm using variables to reference the stateMachine in another file like so:

```
stepFunctions:
  stateMachines: ${file(stack.${opt:stack}.yaml):stepFunctions.stateMachines}
```

 _findState wasn't finding my stateMachines because the plugin wasn't interpolating which is why I added this pr.

**Comment by vkkis93** [comment]
It's great that you said about it 
I will look on it.

**Comment by vkkis93** [comment]
Thank you for your PR @ajagnanan .
Works great.
Version 1.0.1 include this fix.

**Pull request merged**
